spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/online_food_db
spring.datasource.username=root
spring.datasource.password=Sethu@2006
spring.jpa.hibernate.ddl-auto=update